[package]
name = "grain"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.2"
indicatif = "0.17.8"
libc = "0.2.159"
mt19937 = "2.0.1"
nalgebra = "0.33.0"
rand = "0.8.5"
rand_distr = "0.4.3"
rayon = "1.10.0"
